### ISSUE TITLE
Mamba in speech separation task

### ISSUE THREAD

**Issue by JusperLee** [yyyujintang/Awesome-Mamba-Papers#12]
You can add two papers that use Mamba in speech separation tasks.

1. [SPMamba: State-space model is all you need in speech separation](https://arxiv.org/abs/2404.02063) [[code]](https://github.com/JusperLee/SPMamba)
2. [Multichannel Long-Term Streaming Neural Speech Enhancement for Static and Moving Speakers](https://arxiv.org/abs/2403.07675) [[code]](https://github.com/Audio-WestlakeU/NBSS)

**Comment by yyyujintang** [comment]
Thank you for sharing! I have updated our project with your paper.
