### ISSUE TITLE
ViM-UNet: Vision Mamba for Biomedical Segmentation

### ISSUE THREAD

**Issue by anwai98** [yyyujintang/Awesome-Mamba-Papers#14]
Hi @yyyujintang,

We have our recent contribution accepted at **MIDL 2024**, I'll leave the relevant links below:
1. Preprint: https://doi.org/10.48550/arXiv.2404.07705
2. Code: https://github.com/constantinpape/torch-em/blob/main/vimunet.md
3. MIDL 2024 Paper: https://openreview.net/forum?id=PYNwysgFeP

Thanks for maintaining this awesome repo! :)

**Comment by yyyujintang** [comment]
Thank you for sharing! I have updated our project with your paper.
