### ISSUE TITLE
Mamaba for Remote Sensing Image Change Captioning

### ISSUE THREAD

**Issue by Chen-Yang-Liu** [yyyujintang/Awesome-Mamba-Papers#15]
RSCaMa: Remote Sensing Image Change Captioning with State Space Model
paper link: https://arxiv.org/abs/2404.18895
code link: https://github.com/Chen-Yang-Liu/RSCaMa

**Comment by yyyujintang** [comment]
Thank you for sharing! I have updated our project with your paper.
