### ISSUE TITLE
I2I-Mamba: Multi-modal medical image synthesis via selective state space modeling

### ISSUE THREAD

**Issue by bilalkabas** [yyyujintang/Awesome-Mamba-Papers#17]
Hi,

Please consider including our recent work, I2I-Mamba, in your collection. Here are the links to the preprint and the GitHub repository:

ArXiv preprint: https://arxiv.org/abs/2405.14022
GitHub repo: https://github.com/icon-lab/I2I-Mamba

Thank you for this collection.

**Comment by yyyujintang** [comment]
Thank you for sharing! I have updated our project with your paper.
