### ISSUE TITLE
EHRMamba

### ISSUE THREAD

**Issue by Adibvafa** [yyyujintang/Awesome-Mamba-Papers#18]
Hello! We recently posted a cutting-edge application of Mamba on Electronic Health Records (EHR) modeling.
Paper: https://arxiv.org/abs/2405.14567v1
Code: https://github.com/VectorInstitute/odyssey
Project Page: https://vectorinstitute.github.io/EHRMamba

**Comment by yyyujintang** [comment]
Thank you for sharing! I have updated our project with your paper.

**Comment by Adibvafa** [comment]
@yyyujintang Thank you! Could you put it under medical related Mamba models?
