### ISSUE TITLE
Suggestion for Inclusion in the list: Interpretability of Mamba Using LRP

### ISSUE THREAD

**Issue by FarnoushRJ** [yyyujintang/Awesome-Mamba-Papers#24]
Hi,

thank you for this great list. I’d like to suggest an addition. Please consider including our recent research on the interpretability of Mamba using Layer-wise Relevance Propagation (LRP).

Link = [ MambaLRP: Explaining Selective State Space Sequence Models ](https://arxiv.org/pdf/2406.07592), [code](https://github.com/FarnoushRJ/MambaLRP)

> Abstract:
> Recent sequence modeling approaches using Selective State Space Sequence Models, referred to as Mamba models, have seen a surge of interest. These models allow efficient processing of long sequences in linear time and are rapidly being adopted in a wide range of applications such as language modeling, demonstrating promising performance. To foster their reliable use in real-world scenarios, it is crucial to augment their transparency. Our work bridges this critical gap by bringing explainability, particularly Layer-wise Relevance Propagation (LRP), to the Mamba architecture. Guided by the axiom of relevance conservation, we identify specific components in the Mamba architecture, which cause unfaithful explanations. To remedy this issue, we propose MambaLRP, a novel algorithm within the LRP framework, which ensures a more stable and reliable relevance propagation through these components. Our proposed method is theoretically sound and excels in achieving state-of-the-art explanation performance across a diverse range of models and datasets. Moreover, MambaLRP facilitates a deeper inspection of Mamba architectures, uncovering various biases and evaluating their significance. It also enables the analysis of previous speculations regarding the long-range capabilities of Mamba models.

Thank you for considering my suggestion!

Best regards,
Farnoush

**Comment by yyyujintang** [comment]
Thank you! I've added it to the interpretability category.
