### ISSUE TITLE
Add one paper

### ISSUE THREAD

**Issue by BIT-MJY** [yyyujintang/Awesome-Mamba-Papers#32]
(Arxiv 24.09.05) MADiff: Motion-Aware Mamba Diffusion Models for Hand Trajectory Prediction on Egocentric Videos [Paper](https://arxiv.org/abs/2409.02638)

probably in the "diffusion" category. Thanks!

**Comment by yyyujintang** [comment]
Thank you! I've added it to the diffusion category.
