### ISSUE TITLE
[CVPR'24 Spotlight] State Space Models for Event Cameras

### ISSUE THREAD

**Issue by NikolaZubic** [yyyujintang/Awesome-Mamba-Papers#33]
Dear @yyyujintang , our work has been a spotlight at CVPR 2024. We would like if you could add it to the list:

https://arxiv.org/abs/2402.15584
https://github.com/uzh-rpg/ssms_event_cameras

Best,
Nikola.

**Comment by yyyujintang** [comment]
Thank you! I've added it to the Vision Category.
