### ISSUE TITLE
[State Space Model (SSM)] S7: Selective and Simplified State Space Layers for Sequence Modeling

### ISSUE THREAD

**Issue by NikolaZubic** [yyyujintang/Awesome-Mamba-Papers#34]
Dear @yyyujintang  ,

Here is our new paper on the S7 architecture:
S7: Selective and Simplified State Space Layers for Sequence Modeling
https://arxiv.org/abs/2410.03464

**Comment by yyyujintang** [comment]
Thank you! I've added it to the SSM Category.
